name: oref
description: A high-performance Flutter state management tool, Oref is one of the fastest Flutter signals and state management solutions.

version: 2.10.0
repository: https://github.com/medz/oref

topics:
  - signals
  - reactive
  - state-management
  - alien-signals

funding:
  - https://github.com/sponsors/medz
  - https://opencollective.com/openodroe

environment:
  sdk: ^3.13.0
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter
  alien_signals: ^2.3.2
  analyzer: ^14.4.0
  analysis_server_plugin: ^0.3.23
  analyzer_plugin: ^0.14.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
